find_package(PkgConfig QUIET)
# 查找 SDL3 是否安装
if(PKG_CONFIG_FOUND)
  pkg_check_modules(SDL3 QUIET IMPORTED_TARGET sdl3)
  if(SDL3_FOUND)
    link_libraries(PkgConfig::SDL3 ${MK_LINK_LIBRARIES})
    message(STATUS "found library: ${SDL3_LIBRARIES}")
  endif()
endif()

if(NOT SDL3_FOUND)
  find_package(SDL3 QUIET)
  if(SDL3_FOUND)
    include_directories(SYSTEM ${SDL3_INCLUDE_DIR})
    link_libraries(${SDL3_LIBRARY} ${MK_LINK_LIBRARIES})
    message(STATUS "found library: ${SDL3_LIBRARY}")
  endif()
endif()

if(NOT SDL3_FOUND)
  message(WARNING "${APP_NAME} disabled, please install sdl3 ffmpeg/libavcodec ffmpeg/libavutil ffmpeg/libswresample")
  return()
endif()

set(SRC_LIST "SDLCapture.cpp" "SDLCapture.h")
#aux_source_directory(. SRC_LIST)
add_executable(uvc_server ${SRC_LIST} uvc_server.cpp)

add_executable(sdl_player ${SRC_LIST} sdl_player.cpp)
if(MSVC)
  set_target_properties(sdl_player PROPERTIES LINK_FLAGS "/SAFESEH:NO /SUBSYSTEM:WINDOWS")
endif()